{
    'name': 'KASCCO Website Snippets',
    'version': '16.0.1.0.0',
    'summary': """KASCCO Website Snippets""",
    'category': 'Website',
    'description': """""",
    'author': '',
    'company': '',
    'maintainer': '',
    'website': "",
    'depends': ['website', 'base', 'website_sale', 'hr', 'hr_attendance', 'project', 'contacts'],
    'data': [
             'security/ir.model.access.csv',
             'views/customer_snippet.xml',
             'views/customer_snippet_templates.xml',
             'views/supplier_snippet_templates.xml',
             'views/res_partner.xml',
             'views/settings.xml',
             'views/web_partner_views.xml',
             'data/schedule_report.xml',
             'data/mail_template.xml',
             'report/report.xml',
             ],
    'assets': {
        'web.assets_frontend': [
            'ks_website_snippets/static/src/css/customer_snippet.css',
            'ks_website_snippets/static/src/xml/hierarchy_template.xml',
            'ks_website_snippets/static/src/xml/employee_snippet.xml',
            'ks_website_snippets/static/src/js/customer_snippet.js',
            'ks_website_snippets/static/src/js/employee_snippet.js',
        ],
        'website.assets_wysiwyg': [
            '/ks_website_snippets/static/src/js/options.js',
            '/ks_website_snippets/static/src/js/supplier_options.js',
            'ks_website_snippets/static/src/js/partner_snippet.js',
        ],
        'web.assets_backend': [
            'ks_website_snippets/static/src/xml/customer_snippet_templates.xml',
            'ks_website_snippets/static/src/xml/partner_snippet_tmp.xml',
            'ks_website_snippets/static/src/xml/supplier_snippet_template.xml',
            'ks_website_snippets/static/src/xml/hierarchy_template.xml',
        ],
    },
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': False,
}
